### ISSUE TITLE
Updating Billing Library of the Glassfy Android SDK

### ISSUE THREAD

**Issue by simaxme** [glassfy/android-sdk#2]
This issue is related to [this capacitor-plugin-glassfy issue](https://github.com/glassfy/capacitor-plugin-glassfy/issues/17).

The current used Billing Library in your Android SDK does use the Version 4. This version is outdated and cannot be used in a couple of months. It would be nice if you could update the billing library in your SDK because this is a very serious issue.

The related line is [here](https://github.com/glassfy/android-sdk/blob/3f3821ac516023ea0c65430e99d8ab2d09d28db6/glassfy/build.gradle.kts#LL68C52-L68C52)

This issue should also fix the other issue as [you are using this sdk for your capacitor plugin](https://github.com/glassfy/capacitor-plugin-glassfy/blob/071e4a96f238bf262b19b262099ac0366a165667/android/build.gradle#LL69C38-L69C38)

**Comment by JaHollTV** [comment]
This issue is urgent! No Apps will be able to be deployed to Google Play after September 2023.

All Developers and companies which are using Glassfy will need some time to update their Apps. So please update the Billing library as soon as possible.

**Comment by marcopifferi** [comment]
We just released the Android SDK 1.5.0 that Support Google Billing 5.0

The current version still require the product to be backward compatible in the Play Store but it is fully compliant with Google requirements.
No changes are required to apps using Glassfy: just link the new SDK.
In the coming weeks we will release a new update that fully support the base plan and the offering from the play store account.
